# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
plugins:
 - table
 - fullscreen
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: true



